### ISSUE TITLE
'Session_ID' to 'username'

### ISSUE THREAD

**Issue by sherl0ck17** [powahftw/InstaStories#21]
Hello @powahftw, is there a way to convert the filename that's being created to change from 'session_id' to it's actual 'username' instead, for exp, '6860189' to 'justinbieber'?

Thank you!

**Comment by powahftw** [comment]
Hey @sherl0ck17 , sure you can change line 170 of Instastories.py to use username instead of user_id. 

It was like that in the past (see commit https://github.com/powahftw/InstaStories/commit/6e98cdd327225ef4e7984a568dae2a8c1210b6bb) 

If you use the flask website other stuff might need to be changed for it to work as expected.
